### Crear el primer Expediente (Caso)
POST {{backend_HostAddress}}/api/casos
Content-Type: application/json

{
  "id_usuario": 1,
  "titulo": "Divorcio por Mutuo Consentimiento",
  "descripcion": "El cliente y su cónyuge han acordado los términos del divorcio y separación de bienes.",
  "id_estatus": 1,
  "fechaInicio": "2026-03-17T10:00:00Z",
  "id_RamaJuridica": 1
}